version: '3.8'
services:
  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:3001}
      - NEXT_PUBLIC_CONTRACT_ADDRESS=0xc6FD8fa40ED06D21FDCA1961B75a7170991422D0
      - NEXT_PUBLIC_CHAIN_ID=16661
      - NEXT_PUBLIC_RPC_URL=https://evmrpc.0g.ai
    depends_on:
      - backend

  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - backend-data:/app/data
      - backend-uploads:/app/uploads
    environment:
      - PORT=3001
      - NODE_ENV=production
      - JWT_SECRET=4ecfdde5f9639bfacd35a7c2d48788df8ae4e606bac5bae09590369dcecf6727
      - LLM_API_KEY=${LLM_API_KEY}
      - LLM_API_URL=https://api.z.ai/api/paas/v4/chat/completions
      - RPC_URL=https://evmrpc.0g.ai
      - CONTRACT_ADDRESS=0xc6FD8fa40ED06D21FDCA1961B75a7170991422D0
      - PRIVATE_KEY=${PRIVATE_KEY}
      - CHAIN_ID=16661
      - PAPER_ANCHOR_ADDRESS=0x335C0b922325dd5214Bb9e7CDcA6a61A24B0d8C7
      - NFT_CONTRACT_ADDRESS=0x010a70be3D661B98f69Ab4De1e213CA56C90de4a
      - AGENT_NFT_ADDRESS=0x9ebf66F0818db38BD55f1337b8a83E97c8e095C6
      - AGENT_TIP_JAR_ADDRESS=0x7e59BB6ff6C58D03C07bdFC35040b4A08779A9f6
      - AGENTIC_ID_ADDRESS=0x82c5e31880929de181E5DF78D60f342168d18115
      - PONDER_URL=http://172.19.0.1:42069

  indexer:
    build:
      context: .
      dockerfile: indexer/Dockerfile
    restart: unless-stopped
    ports:
      - "42069:42069"

volumes:
  backend-data:
  backend-uploads:
