version: '3.8'
services:
  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
      - NEXT_PUBLIC_CONTRACT_ADDRESS=0xF5E23E98a6a93Db2c814a033929F68D5B74445E2
      - NEXT_PUBLIC_CHAIN_ID=16602
      - NEXT_PUBLIC_RPC_URL=https://evmrpc-testnet.0g.ai
    depends_on:
      - backend

  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - backend-data:/app/data
      - backend-uploads:/app/uploads
    environment:
      - PORT=3001
      - NODE_ENV=production
      - LLM_API_KEY=${LLM_API_KEY}
      - LLM_API_URL=https://api.z.ai/api/paas/v4/chat/completions
      - RPC_URL=https://evmrpc-testnet.0g.ai
      - CONTRACT_ADDRESS=0xF5E23E98a6a93Db2c814a033929F68D5B74445E2
      - PRIVATE_KEY=${PRIVATE_KEY}
      - CHAIN_ID=16602
      - PAPER_ANCHOR_ADDRESS=0xbb9775A363c63b84e7e7a949eE410eDd1eCB1FCE
      - NFT_CONTRACT_ADDRESS=0x5495b92aca76B4414C698f60CdaAD85B364011a1

volumes:
  backend-data:
  backend-uploads:
