// Seed 11 additional papers for demo
const Database = require("better-sqlite3");
const path = require("path");
const db = new Database(path.join(__dirname, "data", "rumahpeneliti.db"));

const papers = [
  { title: "Zero-Knowledge Proofs for Privacy-Preserving Machine Learning", authors: "Dr. Wei Zhang, Prof. Maria Santos, Rahul Kumar", abstract: "This paper explores the intersection of zero-knowledge proofs and machine learning, proposing a framework for verifying ML model inference without revealing the model parameters or input data. The approach enables trustless AI verification on decentralized networks.", category: "cryptography", difficulty: "advanced", tags: ["zkp", "machine-learning", "privacy", "verification"] },
  { title: "Cross-Chain Interoperability: A Comparative Analysis of Bridge Protocols", authors: "Dr. Alex Thompson, Yuki Tanaka, Fatima Al-Rashid", abstract: "We present a comprehensive comparison of 12 cross-chain bridge protocols, evaluating security, latency, throughput, and decentralization. Our analysis reveals fundamental trade-offs between trust minimization and practical performance.", category: "blockchain", difficulty: "intermediate", tags: ["cross-chain", "bridges", "interoperability", "defi"] },
  { title: "Decentralized Autonomous Organizations: Governance Patterns and Failure Modes", authors: "Prof. Lisa Chen, Dr. Oleg Petrov, Amara Johnson", abstract: "An empirical study of 150 DAO governance events revealing common failure patterns including voter apathy, plutocratic capture, and coordination failures. We propose a novel quadratic voting mechanism with reputation-weighted influence.", category: "governance", difficulty: "intermediate", tags: ["dao", "governance", "voting", "mechanism-design"] },
  { title: "Neural Architecture Search on Resource-Constrained Edge Devices", authors: "Dr. Priya Sharma, Jens Mueller, Dr. Carlos Rivera", abstract: "We present EdgeNAS, a neural architecture search framework optimized for edge devices with less than 2GB RAM. Our approach achieves 97.3% of cloud-based accuracy while reducing model size by 85% through novel pruning and quantization techniques.", category: "machine-learning", difficulty: "advanced", tags: ["nas", "edge-computing", "model-compression", "optimization"] },
  { title: "Tokenomics 2.0: Designing Sustainable Cryptoeconomic Systems", authors: "Dr. Robert Kim, Aisha Patel, Thomas Bergström", abstract: "This paper introduces a unified framework for analyzing token economic sustainability, combining game theory, mechanism design, and empirical data from 500+ token launches. We identify key predictors of long-term token viability.", category: "economics", difficulty: "beginner", tags: ["tokenomics", "cryptoeconomics", "sustainability", "defi"] },
  { title: "Federated Learning with Differential Privacy Guarantees", authors: "Prof. Sarah Williams, Dr. Ming Liu, Giovanni Rossi", abstract: "We propose a novel federated learning protocol that provides formal (ε,δ)-differential privacy guarantees while maintaining model accuracy within 2% of centralized training. Our approach reduces communication overhead by 60% compared to existing methods.", category: "machine-learning", difficulty: "advanced", tags: ["federated-learning", "differential-privacy", "distributed-systems"] },
  { title: "Web3 Identity: Self-Sovereign Identity Systems on Blockchain", authors: "Dr. Natalia Popov, James Okafor, Dr. Hana Yoshida", abstract: "A systematic review of self-sovereign identity implementations across 8 blockchain platforms. We evaluate verifiable credential standards, DID methods, and zero-knowledge identity proofs, proposing an interoperability layer for cross-chain identity.", category: "identity", difficulty: "intermediate", tags: ["ssi", "identity", "did", "verifiable-credentials"] },
  { title: "Scalable Consensus: Proof-of-Stake in Practice", authors: "Dr. Michael Torres, Elena Volkov, Dr. Kwame Asante", abstract: "An in-depth performance analysis of five major PoS consensus protocols under realistic network conditions. Our benchmark reveals that finality time, not throughput, is the primary bottleneck for decentralized applications requiring high responsiveness.", category: "blockchain", difficulty: "intermediate", tags: ["consensus", "proof-of-stake", "scalability", "performance"] },
  { title: "AI-Powered Smart Contract Auditing: A Multi-Agent Approach", authors: "Dr. David Park, Sofia Martinez, Dr. Raj Patel", abstract: "We present a multi-agent AI system for automated smart contract auditing that combines static analysis, symbolic execution, and LLM-based reasoning. The system detects 94% of known vulnerability patterns with a false positive rate below 3%.", category: "security", difficulty: "advanced", tags: ["smart-contracts", "auditing", "ai", "multi-agent", "security"] },
  { title: "Decentralized Data Marketplaces: Pricing Models and Incentive Alignment", authors: "Prof. Anna Schmidt, Dr. Youssef Hassan, Linda Chen", abstract: "This paper examines economic models for decentralized data marketplaces, proposing a dynamic pricing mechanism based on data quality scores and demand prediction. Our model increases marketplace efficiency by 40% in simulated environments.", category: "economics", difficulty: "beginner", tags: ["data-marketplace", "pricing", "incentives", "decentralization"] },
  { title: "On-Chain Machine Learning: Training Models in Smart Contracts", authors: "Dr. Kevin Zhou, Maria Garcia, Dr. Olga Ivanova", abstract: "We demonstrate the feasibility of on-chain ML training using optimized opcodes and storage patterns. Our approach trains logistic regression models entirely within EVM execution, achieving convergence in under 500K gas for small datasets.", category: "blockchain", difficulty: "advanced", tags: ["on-chain-ml", "evm", "smart-contracts", "machine-learning"] },
];

const articles_data = [
  { title: "How Zero-Knowledge Proofs Could Revolutionize AI Trust", summary: "Zero-knowledge proofs offer a breakthrough path for verifying AI model outputs without exposing proprietary parameters, opening doors for trustless decentralized inference.", key_takeaways: ["ZK-ML verification enables trustless AI without revealing model weights", "Proof generation overhead reduced by 75% using recursive SNARKs", "Practical applications in healthcare, finance, and autonomous systems", "Integration with 0G Compute enables verifiable AI marketplace"], body: "The convergence of zero-knowledge cryptography and machine learning represents one of the most exciting frontiers in decentralized AI. This research demonstrates that it is now feasible to generate cryptographic proofs of ML inference correctness, allowing third parties to verify that a model produced a specific output for a given input — without learning anything about the model itself.\n\nThe implications are profound. AI service providers can prove their models are performing correctly without exposing proprietary weights. Users can verify inference results without trusting the provider. Regulators can audit AI systems without accessing sensitive data.\n\nThe researchers achieve this through recursive SNARK constructions that dramatically reduce proof generation overhead. While earlier ZK-ML systems required minutes to generate proofs, this approach brings it down to seconds for common model architectures.\n\nIntegration with decentralized compute networks like 0G Compute creates a powerful combination: AI inference runs on distributed nodes, and each inference generates a verifiable proof stored on-chain. This creates an auditable trail of AI decisions that anyone can independently verify.\n\nThe researchers identify healthcare diagnostics, financial risk assessment, and autonomous vehicle control as the most promising near-term applications. In each case, the ability to verify AI decisions without compromising privacy or proprietary interests addresses a critical market need." },
  { title: "The Bridge Problem: Why Cross-Chain Still Breaks", summary: "A systematic analysis reveals that cross-chain bridges remain the weakest link in the multi-chain ecosystem, with fundamental trade-offs between security and usability.", key_takeaways: ["12 major bridge protocols analyzed across 6 security dimensions", "65% of bridges sacrifice decentralization for speed", "Trustless bridges show 3-5x higher latency", "Novel hybrid architecture proposed combining optimistic and ZK verification"], body: "Cross-chain bridges are supposed to connect the fragmented blockchain ecosystem, but a comprehensive new study reveals they remain its most dangerous weak point. Analyzing 12 major bridge protocols across security, latency, throughput, and decentralization dimensions, the researchers paint a sobering picture.\n\nThe fundamental tension is clear: bridges that prioritize speed tend to centralize trust in a small set of validators, creating attractive targets for attackers. The $600M+ Ronin bridge hack and the $320M Wormhole exploit are not anomalies — they are consequences of architectural choices that trade security for performance.\n\nTrustless bridges using light client verification offer the strongest security guarantees but suffer from 3-5x higher latency compared to trusted validator sets. For DeFi applications where seconds matter, this creates a difficult trade-off.\n\nThe researchers propose a novel hybrid architecture that combines optimistic verification for fast transfers with ZK proof fallbacks for high-value transactions. Early benchmarks show this approach can achieve sub-second finality for routine transfers while maintaining full verification for amounts above configurable thresholds." },
  { title: "When DAOs Fail: Lessons from 150 Governance Crises", summary: "An unprecedented analysis of DAO governance failures reveals systemic patterns that threaten the viability of decentralized organizations.", key_takeaways: ["Voter apathy averages 87% across analyzed DAOs", "Whales control 60%+ voting power in 73% of DAOs", "Quadratic voting with reputation weighting shows 40% improvement", "Emergency governance mechanisms critically underdeveloped"], body: "Decentralized Autonomous Organizations promise democratic governance, but a new empirical study of 150 DAO governance events reveals troubling patterns. The data shows that the gap between DAO ideals and reality remains vast.\n\nVoter apathy is the most pervasive problem. Across the DAOs studied, average participation in governance votes was just 13%. Even for high-stakes decisions involving treasury allocations exceeding $1M, participation rarely exceeded 30%.\n\nMore concerning is the concentration of power. In 73% of analyzed DAOs, the top 10 token holders control more than 60% of voting power. This creates de facto plutocratic governance that can be indistinguishable from traditional corporate structures.\n\nThe researchers propose a novel governance mechanism combining quadratic voting with reputation-weighted influence earned through sustained participation and contributions. Simulation results show this approach improves outcome diversity by 40% and reduces plutocratic capture while maintaining token-holder alignment." },
  { title: "Tiny Models, Big Results: AI at the Edge Gets Real", summary: "A new framework for neural architecture search on resource-constrained devices achieves near-cloud accuracy with 85% smaller models.", key_takeaways: ["EdgeNAS achieves 97.3% of cloud accuracy on devices with <2GB RAM", "Model size reduced by 85% through novel pruning techniques", "Quantization-aware search finds hardware-optimal architectures", "Deployed successfully on Raspberry Pi and mobile devices"], body: "Running sophisticated AI models on edge devices has long been a pipe dream, but new research from a team of computer scientists makes it a practical reality. Their framework, EdgeNAS, automatically discovers neural network architectures specifically optimized for devices with severe memory and compute constraints.\n\nThe key innovation is a quantization-aware search process that simultaneously optimizes model architecture and numerical precision. Traditional approaches first design a model, then compress it — often losing critical accuracy. EdgeNAS instead searches directly in the space of quantized operations, finding architectures that are inherently efficient from the start.\n\nOn a benchmark suite spanning image classification, object detection, and natural language processing, EdgeNAS achieves 97.3% of cloud-based model accuracy while reducing model size by 85%. The resulting models run comfortably on devices with less than 2GB of RAM, including Raspberry Pi 4 and mid-range Android phones.\n\nThe implications for decentralized AI are significant. Edge-deployed models reduce dependence on cloud infrastructure, lower latency for real-time applications, and improve privacy by keeping data on-device." },
  { title: "Designing Token Economies That Don't Collapse", summary: "A data-driven framework identifies the key factors that separate sustainable token economies from those that fail within the first year.", key_takeaways: ["73% of tokens lose 90%+ value within 18 months of launch", "Three key predictors of sustainability identified from 500+ launches", "Utility-driven demand outperforms speculation by 4x in long-term value", "Novel sustainability scoring model achieves 89% prediction accuracy"], body: "The token economy landscape is littered with failures. A new comprehensive study analyzing over 500 token launches reveals that 73% lose more than 90% of their value within 18 months. But the researchers didn't just document failures — they identified what separates the survivors.\n\nThree factors emerge as critical predictors of sustainability: genuine utility demand (not just speculation), balanced token distribution avoiding whale concentration, and transparent vesting schedules that prevent insider dumping. Tokens scoring highly on all three factors showed 4x better value retention over 24 months.\n\nThe researchers formalize these insights into a Sustainability Scoring Model (SSM) that achieves 89% accuracy in predicting which tokens will maintain value above their ICO price after one year. The model considers 14 quantitative metrics spanning distribution, velocity, utility, and governance.\n\nFor builders in the Web3 space, the message is clear: token design is not an afterthought. It requires the same rigor as product design, with sustainability as the primary objective rather than short-term fundraising maximization." },
  { title: "Private by Design: Federated Learning Meets Differential Privacy", summary: "A new federated learning protocol achieves formal privacy guarantees while maintaining 98% of centralized training accuracy.", key_takeaways: ["Formal (ε,δ)-differential privacy guarantees during federated training", "Model accuracy within 2% of centralized baseline", "Communication overhead reduced by 60% through gradient compression", "Tested on medical imaging and NLP benchmarks"], body: "Training AI models on sensitive data without compromising individual privacy is one of the defining challenges of our era. This research presents a breakthrough federated learning protocol that provides mathematical privacy guarantees while maintaining practical model accuracy.\n\nThe key innovation is an adaptive clipping mechanism that automatically calibrates the amount of noise added to gradient updates based on the sensitivity of each training round. Unlike previous approaches that apply uniform noise across all rounds, this adaptive approach preserves more signal in early training while maintaining privacy budgets.\n\nCombined with gradient compression techniques, the protocol also reduces communication overhead by 60% — a critical improvement for federated networks with bandwidth-constrained participants. The researchers demonstrate the approach on medical imaging classification and natural language processing benchmarks, achieving within 2% of centralized training accuracy while formally guaranteeing that no individual training example can be inferred from the final model.\n\nThe implications for decentralized AI are particularly exciting. This approach could enable collaborative model training across institutions, hospitals, or even individual devices without any participant needing to trust the others with their raw data." },
  { title: "Who Owns Your Digital Identity? The Answer is Changing", summary: "A systematic review of self-sovereign identity across 8 blockchain platforms reveals both progress and persistent interoperability challenges.", key_takeaways: ["8 major SSI implementations compared across 12 evaluation criteria", "DID method fragmentation remains the biggest barrier to adoption", "ZK identity proofs enable selective disclosure without data exposure", "Proposed interoperability layer connects disparate DID systems"], body: "Digital identity is broken. Every website holds a copy of your personal data, every login creates a new vulnerability, and data breaches affect billions of people annually. Self-sovereign identity (SSI) on blockchain promises to fix this by putting users in control of their own credentials.\n\nThis systematic review evaluates SSI implementations across eight blockchain platforms, examining verifiable credential standards, DID methods, and emerging zero-knowledge identity proofs. The good news is that the technology has matured significantly — W3C standards for verifiable credentials and DIDs provide a solid foundation.\n\nThe bad news is fragmentation. Different platforms implement different DID methods, making cross-platform identity verification unnecessarily complex. A credential issued on one blockchain often cannot be verified on another without trusted intermediaries — exactly the problem SSI was supposed to solve.\n\nThe researchers propose an interoperability layer that acts as a universal translator between DID systems. Using hash-linked credential registries and ZK proofs of credential validity, the layer enables cross-chain identity verification without requiring platforms to adopt the same DID method." },
  { title: "Fast Finality: The Real Bottleneck for Blockchain Apps", summary: "Performance benchmarks reveal that consensus finality time, not throughput, is the primary bottleneck for responsive dApps.", key_takeaways: ["5 major PoS protocols benchmarked under realistic network conditions", "Finality time ranges from 1 second to 15 minutes across protocols", "User experience degrades significantly above 4-second finality", "Hybrid finality mechanisms show most promise for practical applications"], body: "Blockchain scalability discussions typically focus on transactions per second (TPS), but new research reveals this is the wrong metric to optimize. The real bottleneck for decentralized applications is finality time — how long until a transaction is truly irreversible.\n\nThe researchers benchmarked five major proof-of-stake consensus protocols under realistic network conditions including geographic distribution, variable latency, and adversarial scenarios. The results show finality times ranging from under 1 second to over 15 minutes, with dramatic differences in user experience.\n\nFor applications like decentralized exchanges, gaming, and payments, user experience degrades significantly when finality exceeds 4 seconds. Users begin double-clicking, abandoning transactions, or losing confidence in the system — even if the transaction eventually confirms.\n\nThe study identifies hybrid finality mechanisms as the most promising path forward. These protocols provide fast probabilistic finality for most transactions while reserving slower deterministic finality for high-value operations. This approach balances speed and security in a way that pure consensus mechanisms cannot." },
  { title: "AI Auditors: Multi-Agent Systems That Find Smart Contract Bugs", summary: "A multi-agent AI system combining static analysis, symbolic execution, and LLM reasoning detects 94% of known vulnerability patterns.", key_takeaways: ["Three specialized AI agents work in parallel for comprehensive coverage", "94% detection rate on known vulnerability patterns", "False positive rate below 3% — 5x better than single-agent approaches", "Processes typical contract in under 60 seconds"], body: "Smart contract auditing is expensive, slow, and error-prone. Professional audits cost $50K-$500K and take weeks. A new multi-agent AI system promises to democratize access to high-quality contract analysis.\n\nThe system deploys three specialized agents that work in parallel: a static analysis agent that examines code patterns, a symbolic execution agent that explores possible execution paths, and an LLM reasoning agent that understands semantic context and business logic vulnerabilities. Each agent brings different strengths, and their combined coverage exceeds any single approach.\n\nOn a benchmark of 50,000 smart contracts with known vulnerabilities, the system achieves a 94% detection rate with a false positive rate below 3%. This represents a 5x improvement in precision over single-agent approaches and approaches the accuracy of experienced human auditors for common vulnerability classes.\n\nThe multi-agent architecture is key to this performance. Static analysis catches syntax-level issues, symbolic execution finds mathematical edge cases, and the LLM agent catches logic errors that require understanding of intent. When all three agents agree on a finding, confidence is extremely high.\n\nProcessing a typical smart contract takes under 60 seconds, making it practical for CI/CD pipelines and real-time development workflows. The researchers envision a future where every contract deployment is preceded by an automated AI audit." },
  { title: "Selling Data Decentralized: A Better Pricing Model", summary: "Dynamic pricing based on data quality and demand prediction increases marketplace efficiency by 40% in simulated environments.", key_takeaways: ["Quality-scored dynamic pricing outperforms fixed pricing by 40%", "Incentive alignment prevents data poisoning and low-quality submissions", "Demand prediction model achieves 85% accuracy for popular data categories", "Deployed as smart contracts for trustless execution"], body: "Data is the oil of the AI age, but current centralized data marketplaces suffer from opacity, unfair pricing, and platform rent-seeking. This paper introduces a decentralized data marketplace with a novel dynamic pricing mechanism that creates better outcomes for both buyers and sellers.\n\nThe pricing model has two components: a quality score derived from buyer ratings and automated validation checks, and a demand prediction model that adjusts prices based on historical purchasing patterns. High-quality, in-demand data commands premium prices, while low-quality or oversupplied data becomes cheaper — creating natural market incentives for quality.\n\nIn simulated environments with 1,000 data providers and 10,000 buyers, the dynamic pricing model increases marketplace efficiency (measured as total surplus) by 40% compared to fixed pricing. Importantly, it also reduces data poisoning attacks by 70% through a reputation-linked bonding mechanism where providers stake collateral against their data quality claims.\n\nThe entire system is implemented as smart contracts, enabling trustless execution without platform intermediaries. Data providers can list datasets, buyers can purchase access, and quality assessments are aggregated on-chain — all without trusting a central authority." },
  { title: "Training AI Inside Smart Contracts: It's Actually Possible", summary: "Researchers demonstrate on-chain logistic regression training entirely within EVM execution, converging in under 500K gas.", key_takeaways: ["Logistic regression trained entirely in a smart contract", "Convergence achieved in under 500K gas (~$0.05 at current prices)", "Optimized opcodes and packed storage reduce gas by 70%", "Opens possibilities for on-chain adaptive AI systems"], body: "Training machine learning models inside smart contracts sounds impossible — the EVM's computational constraints and gas costs seem prohibitive. But new research demonstrates it's not only possible but practical, at least for certain model architectures.\n\nThe researchers implement logistic regression training using optimized EVM opcodes and tightly packed storage patterns that reduce gas consumption by 70% compared to naïve implementations. For small datasets (up to 1,000 samples with 10 features), the model converges in under 500K gas — roughly $0.05 at current mainnet gas prices.\n\nWhile logistic regression is far from the cutting edge of ML, the demonstration is significant because it proves the concept works. The researchers identify several paths to scaling: layer-2 execution environments with higher gas limits, specialized precompiles for common ML operations, and hybrid approaches where heavy computation happens off-chain with on-chain verification.\n\nThe most exciting applications may be in adaptive smart contracts that learn from on-chain data. Imagine insurance contracts that adjust premiums based on claims history, or lending protocols that refine risk models based on repayment patterns — all verified and enforced by the blockchain itself.\n\nThis work bridges the gap between blockchain's verifiable computation and AI's adaptive capabilities, pointing toward a future where smart contracts are not just deterministic programs but learning systems." },
];

const wallets = [
  "0xabcdef1234567890abcdef1234567890abcdef12",
  "0x1234567890abcdef1234567890abcdef12345678",
  "0x7AefA5B4fE9CFaf837CC0a0EbEA2a5a890aFAf55",
  "0x9876defabc1234567890abcdef1234567890abcd",
  "0x567890abcdef1234567890abcdef12345678efab",
  "0xdef1234567890abcdef1234567890abcdef1234",
];

const classifications = [
  { domain: "cryptography", subdomain: "zero-knowledge-proofs", research_type: "theoretical", difficulty: "advanced" },
  { domain: "blockchain", subdomain: "interoperability", research_type: "empirical", difficulty: "intermediate" },
  { domain: "governance", subdomain: "dao-mechanisms", research_type: "empirical", difficulty: "intermediate" },
  { domain: "machine-learning", subdomain: "neural-architecture-search", research_type: "experimental", difficulty: "advanced" },
  { domain: "economics", subdomain: "token-design", research_type: "empirical", difficulty: "beginner" },
  { domain: "machine-learning", subdomain: "federated-learning", research_type: "experimental", difficulty: "advanced" },
  { domain: "identity", subdomain: "self-sovereign-identity", research_type: "systematic-review", difficulty: "intermediate" },
  { domain: "blockchain", subdomain: "consensus-protocols", research_type: "empirical", difficulty: "intermediate" },
  { domain: "security", subdomain: "smart-contract-auditing", research_type: "experimental", difficulty: "advanced" },
  { domain: "economics", subdomain: "data-marketplaces", research_type: "theoretical", difficulty: "beginner" },
  { domain: "blockchain", subdomain: "on-chain-ml", research_type: "experimental", difficulty: "advanced" },
];

const aiScores = [
  { overall: 88, novelty: 91, clarity: 85, methodology: 87, impact: 90 },
  { overall: 82, novelty: 78, clarity: 84, methodology: 80, impact: 86 },
  { overall: 85, novelty: 88, clarity: 82, methodology: 83, impact: 87 },
  { overall: 79, novelty: 76, clarity: 81, methodology: 78, impact: 82 },
  { overall: 76, novelty: 72, clarity: 80, methodology: 74, impact: 78 },
  { overall: 90, novelty: 92, clarity: 88, methodology: 89, impact: 91 },
  { overall: 83, novelty: 80, clarity: 86, methodology: 82, impact: 84 },
  { overall: 77, novelty: 74, clarity: 79, methodology: 76, impact: 80 },
  { overall: 86, novelty: 89, clarity: 83, methodology: 85, impact: 88 },
  { overall: 74, novelty: 70, clarity: 78, methodology: 73, impact: 76 },
  { overall: 87, novelty: 90, clarity: 84, methodology: 86, impact: 89 },
];

const insertPaper = db.prepare("INSERT INTO papers (title, authors, abstract, file_path, storage_hash, price_wei, author_wallet) VALUES (?, ?, ?, ?, ?, ?, ?)");
const insertArticle = db.prepare("INSERT OR REPLACE INTO articles (paper_id, curated_title, summary, key_takeaways, body, tags, is_mock, ai_score, classification, agent_meta) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");

// Get current max paper id to continue from there
const maxId = db.prepare("SELECT MAX(id) as m FROM papers").get().m || 0;
console.log(`Current max paper ID: ${maxId}, inserting 11 more...`);

const transaction = db.transaction(() => {
  for (let i = 0; i < papers.length; i++) {
    const p = papers[i];
    const a = articles_data[i];
    const wallet = wallets[i % wallets.length];
    const hash = "0x" + require("crypto").randomBytes(32).toString("hex");

    const result = insertPaper.run(
      p.title, p.authors, p.abstract, "", hash,
      "1000000000000000", wallet
    );
    const paperId = result.lastInsertRowid;

    insertArticle.run(
      paperId,
      a.title,
      a.summary,
      JSON.stringify(a.key_takeaways),
      a.body,
      JSON.stringify(p.tags),
      i < 2 ? 0 : 1, // first 2 are "real", rest mock
      JSON.stringify(aiScores[i]),
      JSON.stringify(classifications[i]),
      JSON.stringify({ agents: ["summarizer", "scorer", "tagger"], pipeline_ms: 1000 + Math.floor(Math.random() * 3000) })
    );

    console.log(`  ✅ Paper ${paperId}: ${p.title.slice(0, 60)}...`);
  }
});

transaction();

const total = db.prepare("SELECT COUNT(*) as c FROM papers").get().c;
const totalArticles = db.prepare("SELECT COUNT(*) as c FROM articles").get().c;
console.log(`\nDone! Total: ${total} papers, ${totalArticles} articles`);
